version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "direct"
    groups:
      github-actions:
        update-types:
          - "minor"

  - package-ecosystem: "pip"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "direct"
    groups:
      cargo:
        update-types:
          - "minor"
