version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "direct"
    groups:
      github-actions:
        patterns:
          - "*"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"

  - package-ecosystem: "pip"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "direct"
    groups:
      pip:
        patterns:
          - "*"
    versioning-strategy: "increase-if-necessary"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"
